### ISSUE TITLE
Reduce number of shards

### ISSUE THREAD

**Issue by chris-erickson** [nyaruka/rp-indexer#17]
The number of shards is set to `5` which follows what ES used to use as defaults.  As of the most recent version they have reduced this to `1` as most people never touched it and were left with ballooning indexes with no real value.  As of now, they recommend setting this to `1` unless you know you need otherwise.  Also, if you have less than X nodes (we have 2) this doesn't really buy much durability either.  Would like to set this to 1 if you have no issues with that.

https://github.com/nyaruka/rp-indexer/blob/ca85fff79864ea1ce9efb6e3473bf9a3c8c6e814/indexer.go#L410-L414

**Comment by nicpottier** [comment]
I guess I'm not opposed to this but would like to understand the reasoning around changing it. IE, is it causing a problem now? What is the impact of changing it on index size vs before (on fresh builds), etc.. IE, general philosophy is don't futz with what's not broken and this has worked well for us thus far.

**Comment by chris-erickson** [comment]
It's the tyranny of the default - 5 shards was so you could expand to more nodes (something close to 5) and see performance gains without a reindex.  With anything less it's over provisioning and will actually hurt performance, while having higher resource usage.  From [ES 7 release notes](https://www.elastic.co/blog/elasticsearch-7-0-0-released):

> **Default to one shard**
One of the biggest sources of troubles we've seen over the years from our users has been oversharding --- and defaults play a big role in that. In Elasticsearch 6.x and prior, we defaulted to 5 shards by default per index. If you had one daily index for 10 different applications and each had the default of 5 shards, you were creating 50 shards per day and it wasn't long before you had thousands of shards even if you were only indexing a few gigabytes of data per day. Index lifecycle management (ILM) was a first step to help with this: providing native rollover functions to create indexes by size instead of (just) by day and built-in shrink functionality to shrink the number of shards per index. Defaulting indices to 1 shard is the next step in helping to reduce oversharding. Of course, if you have another preferred primary shard count, you can set it via the index settings.

For us specifically, this would let us reduce our ES cluster size needs - we didn't quite realize how over-provisioned it was until the cluster filled up and RP search was broken.  Clearing out duplicate indexes left us with over 80GB per node back, but this is a bit tangential.  It's something around 15GB extra data right now, but as mentioned above, there's no more reason to do 5 than there is 1 (or perhaps two, since we have 2 nodes but I don't know where we land in terms of index size).

```
health status index               uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   contacts_2019_05_06 5M_s8esZRoC-V66RASU45Q   5   1  158040125        13887     33.4gb         17.3gb
```

Given that this is generally being used for offloading db work at search time, I'm not sure why we'd prioritize redundancy and ability to scale to many nodes at the expense of resource usage and performance when using a sufficient number of nodes.

I don't think there is any issue with indexes of differing parameters living side by side, it's mostly abstracted beneath the index API.

**Comment by nicpottier** [comment]
Cool, why don't you give it a go and report back on results?

**Comment by chris-erickson** [comment]
Not sure what you mean - how do I locally rebuild this and do that?

**Comment by nicpottier** [comment]
Can build locally using standard go commands, ie:
`go build github.com/nyaruka/rp-indexer/cmd/rp-indexer`
