### ISSUE TITLE
Support for ElasticSearch v7.x

### ISSUE THREAD

**Issue by tybritten** [nyaruka/rp-indexer#24]
Consider adding support for ElasticSearch v7

**Comment by Boxroma** [comment]
Hey. I am running a fresh install and i noticed issues with creating new indexes in ElasticSearch v7. I wanted to know which version is currently supported.

**Comment by tybritten** [comment]
only ES v6.x is supported today.

**Comment by Boxroma** [comment]
Got it working thanks.
