### ISSUE TITLE
Contacts with ridiculous numeric values don't get indexed

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/rp-indexer#31]
example:

```
"number": 700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by rowanseymour** [comment]
Need to fix this goflow. In ES we're storing numbers as scaled_float which is a `long` scaled by 10000, so I think we have it that number parsing in the engine returns something in the range `-922337203685477.5808` to `922337203685477.5807`

**Comment by rowanseymour** [comment]
Turns out people are using big numbers to model things like ID numbers so instead of trying to limit numbers to a range, for now we're using `ignore_malformed` to at least ensure that these documents are indexed tho without their big numbers.

**Comment by rowanseymour** [comment]
Recently went and manually fixed all the places where strings that look like scientific notation numbers had been parsed as decimals so this shouldn't be a problem now.
